TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += amint2l.db

#protocol files
DATA += amint2l.proto

#=======================================
include $(TOP)/configure/RULES
